CABLE-LSM/CABLE

documentation/cable_ford.md
src/offline/cable_define_types.F90
src/science/albedo/cbl_albedo.F90
src/science/radiation/cbl_init_radiation.F90

Fixes #17
Add some fancy documentation in the radiation to show off how FORD works.
This also changes a few options for FORD configuration: add documentation for PRIVATE procedures, remove pre-processing of the Fortran files.

Create a fancy example

---

src/science/radiation/cbl_init_radiation.F90

The fancy example for the docathon is broken. Fixing the formatting. 

Correct formatting of fancy example

---

documentation/docs/POP-TRENDY/index.md
documentation/mkdocs.yml

Add POP-TRENDY section to documentation site

---

src_pop/core/biogeochem/POP.F90

Fixes #(issue)
- [x ] New or updated documentation

some change from Juergen. Please review.

---

documentation/docs/user_guide/tutorial/compilation.md

committing my intentional error

---

src/science/roughness/cable_roughness.F90

description of cable_roughness with typo

---

.github/workflows/mlc_config.json
documentation/docs/user_guide/tutorial/uber_quick_guide.md
documentation/mkdocs.yml

I want to verify how this documentation process works and also verify the formatting discrepancies between the documentation which we already have on the TRAC.
Discussion in a  breakout room, involving Claire as well, may  be required 
Fixes #(issue)

Test formatting and adding this doccumentation

---

.github/actions/preview/action.yml

This is to try and speed up the build of the preview in pull requests
Fixes #65

Remove FORD search from previews

---

documentation/docs/user_guide/tutorial/compilation.md
documentation/mkdocs.yml

I'm using VS locally to verify the formatting now, so it should have less errors than before. 
Fixes #(issue)
- [ X] The new content is accessible and located in the appropriate section.
- [ X] I have checked that links are valid and point to the intended content.
- [ X] I have checked my code/text and corrected any misspellings

Install compile docs

---

src/offline/cable_input.F90

Comments were added to input loading routines to make the logic and process order more transparent. This will be an ongoing process!
Fixes #47 

Basic commenting in load_parameters and get_parameters_met.

---

src/science/roughness/cbl_hgtAbove_snow.F90
src/science/roughness/cbl_lai_eff.F90

This pull request finishes the documentation for the roughness calculations in CABLE. 
Fixes #71 #72 

Documentation for cbl_hgtAbove_snow and cbl_lai_eff

---

src/science/canopy/cbl_zetar.F90

header information for cbl_zetar

---

documentation/docs/developer_guide/contribution_flowchart.md

Fixing a small mistake in arrow colours crept into the flowchart for editing in PR #82 

Fix line colors in edit flowchart

---

documentation/docs/user_guide/inputs/cable_nml.md

Version of cable_nml.md for initial feedback

---

src/science/canopy/cbl_LAI_canopy_height.F90

Documentation for the routine cbl_LAI_canopy_height.F90
Fixes #93 

first header comments

---

src/science/canopy/cbl_friction_vel.F90

Documentation for main subroutine and 2 associated functions 
Fixes #96

first set of docs for cbl_friction_vel

---

src/science/canopy/cbl_latent_heat.F90

Documentation for the cbl_latent_heat module
Fixes #104 

first comments on cbl_latent_heat

---

src/science/canopy/cbl_qsat.F90

Brief documentation for the two subroutines in this module.  A check is needed on an appropriate reference for the Teten constants and formula.
Fixes #100 

first comments on cbl_qsat

---

documentation/docs/css/cable.css
documentation/mkdocs.yml

Fixes #114 
Add a custom CSS file to expand the width of the page. This might cause issues with viewing the site on mobile but I don't see this use case as being prominent for CABLE's documentation

Fixes #114: Custom width of page

---

src/offline/landuse_inout.F90
src/science/landuse/landuse3.F90
src/science/landuse/landuse_constant.F90

Add comments on "landuse_constant.F90" definitions of all constants
Add an overview of landuse code functions
Fixes #49  

comments on landuse codes

---

documentation/docs/user_guide/inputs/cable_soilparm_nml.md
documentation/docs/user_guide/inputs/pft_params_nml.md

This pull request adds an example namelist file for the CABLE soil parameters and a table that describes the namelist variables.
Some data has been taken from the JULES documentation http://jules-lsm.github.io/latest/namelists/cable_soilparm.nml.html
Fixes #122

Filled in cable soil params page

---

documentation/docs/user_guide/inputs/meteorological_forcing.md
documentation/mkdocs.yml

This pull request adds a description of the meteorological forcing files for CABLE offline.
Fixes #146 
----
:books: Documentation preview :books:: https://cable--148.org.readthedocs.build/en/148/

146 met files description

---

documentation/docs/developer_guide/contribution/testing.md
documentation/mkdocs.yml

Fixes #151
This adds a section to the contribution guidelines to explain what testing is recommended and required.
----
:books: Documentation preview :books:: https://cable--152.org.readthedocs.build/en/152/

WP: Testing guidelines - #151

---

README.md

Update the README since the CABLE code is now in this repository.
----
:books: Documentation preview :books:: https://cable--179.org.readthedocs.build/en/179/

Update README.md for CABLE source

---

scripts/TRENDY_runs/v12/run_TRENDY.sh
scripts/TRENDY_runs/v12/split_landmask.py

Added a python version of the split_landmask.R script built by @ccarouge (with minor modifications to open directories before we write to them). Added lines to the run_TRENDY.sh script demonstrating their usage (lines currently commented out, so original R behaviour is preserved for now). Involves addition of -e <extent> to the split_landmask execution line. Can also utilise the python module contained in the hh5 project, if user has access to said project.

Add python version of split_landmask.R script

---

documentation/docs/user_guide/inputs/pft_params_nml.md

Updated content of pft_params.nml options under User Guide as a side task of another GW-related task.
Added text and tables to provide more and neater content.
----
📚 Documentation preview 📚: https://cable--299.org.readthedocs.build/en/299/

Update content of pft_params.nml options under User Guide

---

documentation/docs/user_guide/inputs/index.md
documentation/docs/user_guide/inputs/restart.md
documentation/docs/user_guide/inputs/surface_forcing.md
documentation/docs/user_guide/outputs/index.md
documentation/mkdocs.yml

Added more structure and documentation to the user guide, together with a few placeholders to be filled soon.
- [X ] New or updated documentation
----
📚 Documentation preview 📚: https://cable--315.org.readthedocs.build/en/315/

Add an "Input files" file to the User Guide

---

src/science/casa-cnp/casa_inout.F90
src/science/casa-cnp/casa_rplant.F90

Fixes #163 
initialization to 1 so is applicable even  IF not over-written by specific case applications. i.e. Will be correct for ESM1.5
Fixes #(issue)
----
📚 Documentation preview 📚: https://cable--274.org.readthedocs.build/en/274/

Reconcile versions of rplant

---

core/biogeochem/CASAONLY_LUC.F90
core/biogeochem/POPLUC.F90
core/biogeochem/casa_cnp.F90
core/biogeochem/casa_variable.F90
offline/cable_LUC_EXPT.F90
offline/cable_driver.F90

Several bug fixes and code changes related to fixing the extent of croplands and their dynamics in CABLE.
- [ v] Bug fix
- [ v] New or updated documentation
- [v ] The new content is accessible and located in the appropriate section.
- [v ] I have checked that links are valid and point to the intended content.
- [v ] I have checked my code/text and corrected any misspellings

Cable pop trendy cropfrac

---

src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_cbm.F90

Incremental update of met%tk  following roughness calculation is removed. See issue #459 and links therein.
Fixes #459
- [Y] The new content is accessible and located in the appropriate section.
- [Y] I have checked that links are valid and point to the intended content.
- [Y] I have checked my code/text and corrected any misspellings
----
📚 Documentation preview 📚: https://cable--461.org.readthedocs.build/en/461/

rm roughness update of met%tk

---

src/science/roughness/cable_roughness.F90

Please see issue #480 for description
Fixes #480 
----
📚 Documentation preview 📚: https://cable--481.org.readthedocs.build/en/481/

esm15 flag to calculate effective LAI

---

src/science/canopy/cable_canopy.F90

[See](https://github.com/CABLE-LSM/ACCESS3-JULES/pull/250) 
Fixes #554 
**2025-02-28 18:28:43,893 - INFO - benchcab.benchcab.py:391 - 0 failed, 168 passed**
----
📚 Documentation preview 📚: https://cable--555.org.readthedocs.build/en/555/

following #220 epot calc in AM3

---

.github/workflows/model-build-test-ci.yml
src/offline/cable_parameters.F90

Fixes #598 
```
2025-07-18 12:54:05,020 - INFO - benchcab.benchcab.py:391 - 0 failed, 168 passed
```
----
📚 Documentation preview 📚: https://cable--599.org.readthedocs.build/en/599/

Correction to zse_vec initialisation
