- .github/actions/publish/action.yml
The file to configure FORD for GW is named GW_ford.md and the action was looking for gw_ford.md
> Fix typo in publish action of documentation

- documentation/docs/user_guide/uber_quick_guide.md
Fix a broken link in the documentation to the fluxnet.org Tumbarumba info page.
https://fluxnet.org/sites/siteinfo/AU-Tum
Fixes #124
> Changed link to Tumbarumba fluxnet info at fluxnet.org

- .github/workflows/pull-request-links.yaml
Adds the [readthedocs preview action](https://github.com/readthedocs/actions/tree/v1/preview) so that documentation preview links are more easily accessible.
Fixes #130
----
:books: Documentation preview :books:: https://cable--133.org.readthedocs.build/en/133/
> Add readthedocs preview action

- documentation/docs/user_guide/index.md
This is to describe the responsibilities of users. Users are defined as people who are using the code but not modifying it.
Fixes #141 
----
:books: Documentation preview :books:: https://cable--142.org.readthedocs.build/en/142/
>  #141- User responsibilities

- documentation/docs/developer_guide/coding_standards.md
Add coding standards information to the Developer's Guide. The original branch was corrupted and it was unclear if the automated tests worked correctly. It was easier to restart than try to resolve within the first branch.
Fixes #97 
----
:books: Documentation preview :books:: https://cable--128.org.readthedocs.build/en/128/
> 97 coding standards rebranch

- src/science/canopy/cbl_latent_heat.F90
The build script fails when building the serial executable and produces the following error:
```
ifort -O2 -fp-model precise  -I/apps/netcdf/4.6.3/include/Intel -c cbl_latent_heat.F90
cbl_latent_heat.F90(21): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ( : % [ . = =>
vkfeopge
----------^
cbl_latent_heat.F90(21): error #6218: This statement is positioned incorrectly and/or has syntax errors.
vkfeopge
--^
compilation aborted for cbl_latent_heat.F90 (code 1)
make: *** [Makefile:167: cbl_latent_heat.o] Error 1
```
This change fixes the syntax error in cbl_latent_heat.F90.
Fixes #153
----
:books: Documentation …
> Fix syntax error in cbl_latent_heat.F90

- src/offline/Makefile
- src/offline/build3.sh
In `build3.sh`, the `-O0` flag (which disables optimisations) is included in the `LDFLAGS` variable. This change removes the `-O0` flag from `LDFLAGS` so that:
1. Compiler specific flags (non `ld` flags) are removed from `LDFLAGS`
2. `-O0` flag is not applied for only a subset of source files.
3. The Makefile rules can be simplified.
See #196 for more details on why the flag should be removed.
Tools for testing binary equivalence (see `ldd`, `nm` and `objdump` tools) show that the following build artifacts differ when comparing against the main branch:
- `cable` (serial executable)
- `cable-mpi` (MPI executable)
- `cable_mpicommon.o`
- `cable_mpimaster.o`
- `cable_mpiworker.o`
- `pop_mpi.o`
Regression tests using [benchcab](https://github.com/CABLE-LSM/benchcab) (bitwise comparison of …
> Remove `-O0` flag from `LDFLAGS`

- src/offline/Makefile
- src/offline/build3.sh
`ld` flags are currently specified incorrectly. For example:
1. `-lnetcdf` is not required since it is a dependency of the netCDF Fortran library - only `-lnetcdff` is needed.
2. `ld` flags are being split across two variables: `LDFLAGS` and `LD` when there should only be one (`LD` typically refers to the path  to the `ld` executable). Having the flags split across two variables allows for the flags to be passed to the compiler in an inconsistent way.
See #198 for more details.
This change removes the `LD` variable and any hard-coded linker flags or include flags in the Makefile or build script. Linker flags and include flags are replaced with a query to `pkg-config` so that the correct flags are used. Using `pkg-config` also insulates the build system from changes to library versions and …
> Fix LDFLAGS definition and usage

- src/params/cable_phys_constants_mod.F90
- src/science/sli/cable_sli_numbers.F90
Change the descriptions for the specific heat for water, snow, ice and air to:
- remote "capacity"
- add a unit
- specify the temperature for the specific heat of water since it is used at 0°C and not the standard 20°C.
This is done for CABLE and SLI.
Reference:   https://www.engineeringtoolbox.com/specific-heat-capacity-water-d_660.html
- [X ] Bug fix
- [ X] The new content is accessible and located in the appropriate section.
- [X ] I have checked that links are valid and point to the intended content.
- [X ] I have checked my code/text and corrected any misspellings
----
📚 Documentation preview 📚: https://cable--214.org.readthedocs.build/en/214/
> Correction to the numerical value of the specific heat of water

- CMakeLists.txt
- build.bash
- documentation/docs/developer_guide/other_resources/build_system.md
- documentation/docs/user_guide/installation.md
This pull request should follow after the CMake implementation (see #200). This change adds the following build system changes:
- List source files in alphabetical order in CMakeLists.txt. The order of source files was previously chosen so that we could demonstrate binary equivalence in executables between the CMake build and the Makefile build.
- Use [`find_package(MPI REQUIRED)`](https://cmake.org/cmake/help/latest/module/FindMPI.html) instead of specifying `mpif90` when invoking `cmake` for MPI case. This is done so that
1. We can create separate targets for the serial and MPI executable and only link against the MPI libraries when needed without relying on the MPI compiler wrapper. This lets us compile all executables (serial and parallel) with a single invocation of CMake.
2. We can …
> Additional CMake changes

- .github/workflows/model-build-test-ci.yml
Making CABLE available as a [spack](https://spack.io/) package allows us to test the model compiles successfully inside a continuous integration (CI) environment which gets triggered automatically on a pull request. This change adds the model build CI workflow developed by the ACCESS-NRI release team to compile CABLE offline via spack (see [build-ci](https://github.com/ACCESS-NRI/build-ci) for more details). This workflow compiles CABLE using the intel compiler. The CI for other compilers will follow after this pull request.
Fixes #202
----
📚 Documentation preview 📚: https://cable--223.org.readthedocs.build/en/223/
> Add model build CI for CABLE offline

- src/offline/cable_define_types.F90
- src/offline/cable_parameters.F90
This pull request is part of integrating the ground water hydrology work of Mengyuan Mu into CABLE, which will take place in a sequence of pull requests. The actual integration project itself was completed back in September 2023. The current work involves just a gradual merge into the main branch. 
1. A new SUBROUTINE GWspatialParameters is introduced in **src/offline/cable_parameters.F90**
2. This subroutine will eventually be called only once, from **src/offline/cable_input.F90**. I will add this call at the appropriate time, but for now the subroutine is inactive
3. Dependencies are introduced in **src/offline/cable_parameters.F90** and **src/offline/cable_define_types.F90** in order for the code to compile successfully (confirmed)
4. This pull request involves only code additions, no …
> Introduce SUBROUTINE GWspatialParameters

- src/offline/CASAONLY_LUC.F90
- src/offline/cable_LUC_EXPT.F90
- src/offline/cable_driver.F90
- src/offline/cable_output.F90
- src/science/casa-cnp/casa_cnp.F90
- src/science/landuse/landuse3.F90
gfortran could not compile the CABLE main branch, neither in release mode (-O3 -Wno-aggressive-loop-optimizations) nor in debug mode (-O -g -pedantic-errors -Wall -W -Wno-maybe-uninitialized -fbacktrace -ffpe-trap=zero,overflow,underflow -finit-real=nan).
The name `mland` was an ambiguous reference in the routine `landuse_allocate_mland` in landuse3.F90 because it is used via landuse_constant and defined in `landuse_allocate_mland`. I renamed it locally to `imland` in the routine.
With this change, the release mode compiled. However there were plenty of 'Nonconforming tab character' and 'continued character constant' in the other files. I removed all that and now it compiles in release and debug mode.
Please add a reviewer when ready for …
> Compile with gfortran

- build.bash
The build script currently does not support MPI builds with the GNU compiler on Gadi. This is due to the `intel-mpi` module being loaded when we should be using an MPI module that is compatible with the chosen compiler. This change loads the `openmpi` module when GNU compilation is enabled in the build script. 
Fixes #239
----
📚 Documentation preview 📚: https://cable--241.org.readthedocs.build/en/241/
> Add support for MPI builds with the GNU compiler

- documentation/docs/user_guide/uber_quick_guide.md
Fixes #(285)
Change Uber Quick guide instructions to run the testcase from src/offline/ since for now CABLE needs the namelists in the run directory.
----
📚 Documentation preview 📚: https://cable--286.org.readthedocs.build/en/286/
> Fix testcase from Uber Quick guide.

- documentation/docs/css/cable.css
Increase the overall width of the page. This removes the large left and right margins and tend to improve the rendering of the tables throughout the documentation.
Fixes #(303)
----
📚 Documentation preview 📚: https://cable--305.org.readthedocs.build/en/305/
> (#303): reducing left and right margins

- documentation/docs/javascripts/mathjax.js
- documentation/mkdocs.yml
Resolves #298 
Recently, the [documentation](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax) for MathJax changed to reset the typeset after instant page load.
Considering that it's a cache issue, we would know for sure that the effect after it's on the main `readthedocs` is built again. Seems to work well for readthedocs PR preview (although they do hard refresh for every new page load)
Relevant issues
- https://github.com/squidfunk/mkdocs-material/issues/6661
- https://github.com/squidfunk/mkdocs-material/issues/6407
----
📚 Documentation preview 📚: https://cable--304.org.readthedocs.build/en/304/
> Auto refresh MathJax on page load

- src/offline/cable_input.F90
The model crashed when trying to run multiple sites in the met data file. This was because ncid_mask was not defined.
Fixes #306
- [X ] Bug fix
----
📚 Documentation preview 📚: https://cable--308.org.readthedocs.build/en/308/
> Defined ncid_mask for met data files with multiple sites. Fixes #306.

- .github/workflows/model-build-test-ci.yml
Issues in the [build-ci](https://github.com/ACCESS-NRI/build-ci) pipeline have now been fixed. This change updates the build-ci version to incorporate these changes.
Fixes #236
----
📚 Documentation preview 📚: https://cable--271.org.readthedocs.build/en/271/
> Update build-ci version

- build.bash
This PR addresses feedback specific to build.bash raised in PR: https://github.com/CABLE-LSM/CABLE/pull/238
Fixes #296 
----
📚 Documentation preview 📚: https://cable--297.org.readthedocs.build/en/297/
> build.bash improvements

- .gitignore
- CMakeLists.txt
- build.bash
PR for porting the CABLE-POP_TRENDY branch to CMake.
**Context:**
- We want to consolidate the build systems across CABLE to use CMake to improve ease of testing with tools such as [benchcab][benchcab] and [spack][spack].
- With the current CABLE-4 development around CABLE-POP_TRENDY, it makes sense to port this branch first.
**Checklist:**
1. Intel compiler (classic)
2. Intel compiler (llvm)
3. GNU compiler
- Model outputs were generated using the [TRENDY_V12][TRENDY_V12] configuration for a reduced domain (`extent="64.0,66.0,60.0,62.0"` in `run_TRENDY.sh`). Model outputs were compared using `nccmp -d <file_a> <file_b>`. The model outputs being compared are all `cru_out_cable_1901_2022.nc` and `cru_out_casa_1901_2022.nc` outputs (as these two files are the final products) for each serial …
> Port branch CABLE-POP_TRENDY to CMake

- src/science/casa-cnp/biogeochem_casa.F90
addendum to #163/#274
Fixes #339
bug fix
- [X ] Bug fix
tag @rkutteh 
----
📚 Documentation preview 📚: https://cable--340.org.readthedocs.build/en/340/
> bug fix rm USE rplant1 and CALL rplant1

- documentation/docs/user_guide/inputs/meteorological_forcing.md
- documentation/docs/user_guide/inputs/pft_params_nml.md
- src/offline/cable.nml
- src/offline/cable_checks.F90
- src/offline/cable_driver.F90
- src/offline/cable_input.F90
Fixes #344. Update the namelist provided with the code for the changes to check%range and other fixes for compatibility with GNU compiler.
I have compiled the code and run the Tumbarumba test case with the updated namelist. The test case finished:
```
Finished.    36.78621      seconds needed for year
Finished.    36.78769      seconds needed for        70128  hours
```
----
📚 Documentation preview 📚: https://cable--345.org.readthedocs.build/en/345/
> Update value for checks%range

- src/offline/cable_driver.F90
- src/offline/cable_iovars.F90
- src/offline/cable_mpimaster.F90
- src/offline/cable_mpiworker.F90
- src/offline/casa_cable.F90
- src/science/casa-cnp/bgcdriver.F90
- src/science/gw_hydro/cable_gw_hydro.F90
- src/science/pop/POP.F90
- src/science/sli/cable_sli_main.F90
- src/science/sli/cable_sli_solve.F90
- src_pop/core/biogeochem/POP.F90
- src_pop/core/biogeochem/POPLUC.F90
- src_pop/core/biogeochem/casa_cnp.F90
Fixes #359 
Changes for checking ranges have changed how the `output%X` logical switches are set. This was not reflected in the MPI driver which meant no outputs were produced from simulations using MPI.
Fix include:
- Add call to `set_group_output_values` in cable_mpimaster.F90.
- Add call to `constant_check_range()` in cable_mpiworker.F90. This check was added during the work to check ranges in the serial version. This has no impact on the CABLE outputs but allows the MPI and serial versions to contain the same functionality.
- Changed the logic for `logn` and `wlogn` settings. `wlogn` variable is removed since all cores can use `logn` to capture their log file unit number. This allows the logs from the check ranges to appear …
> Bug fix: outputs broken in MPI implementation

- src/science/canopy/cable_canopy.F90
A single line bug fix to address cases where the diagnosed screen level temperature does not deviate from the reference level air temperature.  This only impacts some sites with tall vegetation.
Note that this change addresses the immediate issue - other aspects involving code structure and when in the calling sequence the screen level diagnostics should occur have been left untouched.
This is intended as a bug fix impacting only the screen level temperature and humidity - all other variables should remain as before.  However this change is - by design -not bitwise comparable with the MAIN so may fail Benchcab testing.
Fixes #313
benchcab/me.org results: …
> one line bug fix to address screen level temperatures #313

- src/offline/cable.nml
- src/offline/cbl_model_driver_offline.F90
- src/science/canopy/cbl_SurfaceWetness.F90
- src/science/gw_hydro/cable_gw_hydro.F90
- src/science/soilsnow/cbl_surfbv.F90
This PR aims to achieve two tasks
- removing the hard-wired lake index from the offline code (including GW module)
- maintaining lakes at saturation in offline model (soil-snow only)
Fixes #341
Addresses #347
----
📚 Documentation preview 📚: https://cable--348.org.readthedocs.build/en/348/
> fixing broken lake tiles in offline #335 and addresses #347

- src/science/canopy/cable_canopy.F90
- src/science/canopy/cbl_dryLeaf.F90
Fixes #351. 
Move the definition of sum_rad_gradis and sum_rad_rniso out of the NITER loop in `define_canopy()` since these variables do not change in the loop. Having a quick comparison between the outputs before and after this commit [the effect is negligeable](https://github.com/CABLE-LSM/CABLE/pull/352#issuecomment-2249656007).
Use `sum_rad_gradis` and `sum_rad_rniso` as calculated in define_canopy() everywhere in define_canopy(), dryLeaf() and wetLeaf(), instead of recalculating them sometimes.
Move the initialisation of `canopy%DvLitt` and `canopy%kthLitt` to the top of `define_canopy()` since these variables are constant throughout the run. We also want these variables to be defined in all cases to avoid errors in …
> Fix: uninitialised variables in cable_canopy.F90

- src/science/radiation/cbl_init_radiation.F90
Following analysis in CABLE4 and discussion in #354 we should use total SW down in the call to `spitter` and apply the resultant `Fbeam` equally to the visible and near-infrared bands.  The original intent (cable1.4) of spitter is to evaluate the fraction of SW down that is diffuse in nature - via the beam fraction `Fbeam`.  This was evaluated once based on the total shortwave down.  From CABLE2 onwards spitter was called twice - once for the visible and once for the near-infrared components.  However the function itself was not adjusted - the result is that beam fraction is universally smaller than the original intent with unknown impacts on the model trajectory.
This change set reverts the evaluation of `Fbeam` to operate on the total SW down and then applies `Fbeam` equally to the two …
> fix bug in spitter call (MAIN)

- documentation/.readthedocs.yaml
The creation of the call graphs (and others) by FORD in the API documentation was broken since moving to readthedocs. This should solve the issue
Fixes #9
We do not build the graphs in the pull request preview of the documentation since it takes >3 min to build the doc with the graphs. This was tested in this fork: https://github.com/ccarouge/CABLE_test
Result example in the documentation: https://cable-test.readthedocs.io/en/latest/api/proc/bgcdriver.html
----
📚 Documentation preview 📚: https://cable--399.org.readthedocs.build/en/399/
> Create call graphs in doc

- src/coupled/ESM1.5/casa_um_inout.F90
casaflux%frac_sapwood needs to be initialised to 1 for the correct calculation of casaflux%crmplant(:,wood) in casa_rplant when cable_user%CALL_climate is not true.
This had been done in casa_inout at #274 but this subroutine is only used for offline simulations.
This change does the initialisation, in casa_init_pk, for ESM1.5/ESM1.6 cases.
Fixes #373
- [X ] Bug fix
----
📚 Documentation preview 📚: https://cable--374.org.readthedocs.build/en/374/
> Initialise casaflux%frac_sapwood=1 for use in casa_rplant (#373)

- src/science/casa-cnp/casa_cnp.F90
As described in #275, this change reinstates code that had been removed in 2022 with little justification. Reinstating the code provides consistency with ACCESS-ESM1.5 and also with relevant code in src_pop/core/biogeochem. Testing for a small sample of sites showed a large impact if this change was made alone. The related issue (#279) incorrectly calculates btran by summing over layers twice. This calculation is only used if the removed code in #275 is reinstated. Site tests with both changes showed only small differences.
Change only impacts runs with CASA-CNP active.
Also dealt with corrections to comment for subroutine avgsoil as noted in #279 and subroutine casa_coeffsoil (#277).
Fixes #275, #277, #279.
Please delete …
> Reinstate dry and cold stress, remove double summation of btran

- core/biogeophys/cable_common.F90
- offline/cable_LUC_EXPT.F90
- offline/cable_cru_TRENDY.F90
- offline/cable_parameters.F90
The retrieving of dimension IDs from input NetCDF files is inconsistent across the code. Add routines to the ```cable_common``` module to standardise the retrieving of said IDs by searching through a list of possible names for the dimension.
Fixes #(issue)
> Add routine to search for dimension IDs by name.

- offline/cable_input.F90
The counter used to find the temporal index in the Met NetCDF files had a minor bug that appeared when datasets spanned many years and included leap years. The leap year checker was checking against the reference year every time, rather than the iterating year.
Fix is a one-liner.
Fixes #([418](https://github.com/CABLE-LSM/CABLE/issues/418))
> One liner fix of leap year bug

- src/science/casa-cnp/casa_cnp.F90
Removed two ifdef ESM15 cases related to the use of xkpsorb. The ESM15 code option is inconsistent with
how xkpsorb is input in the CABLE3 code.
Fixes #283
- [X ] Bug fix
----
📚 Documentation preview 📚: https://cable--375.org.readthedocs.build/en/375/
> Remove ESM15 case as inconsistent with current input of xkpsorb (#283)

- src/offline/cable_mpidrv.F90
- src/offline/cable_mpimaster.F90
- src/offline/cable_mpiworker.F90
- src/offline/cable_write.F90
This PR fixes compilation with gfortran. I also fixes several compiler warnings (mostly about unused variables) in the MPI master/driver modules.
----
📚 Documentation preview 📚: https://cable--410.org.readthedocs.build/en/410/
> Fix gfortran compilation and some warnings

- offline/cable_cru_TRENDY.F90
- offline/cable_driver.F90
- offline/cable_input.F90
Piping the BIOS met inputs (the AGCD dataset) through the routines developed for the CRU routines. There are two options:
1. Make some adjustments to the existing CRU routines to have different options for weather generators, so that it uses the appropriate fields to prepare the weather generator.
2. Leave the BIOS met routines where they are, but make the file look very similar to the ```offline/cable_cru_TRENDY.F90``` file.
Upside of 1 is that it paves the way for work necessary in the long term for generalising inputs. Only upside to 2 is that is it _probably_ easier, but not necessarily. Both approaches require some thorough investigation to determine which bits of the BIOS init routines are only relevant to the met …
> Pipe BIOS met data through CRU routines for weather generation

- documentation/docs/user_guide/inputs/pftlookup_csv.md
- src/science/casa-cnp/casa_cnp.F90
In casa_delsoil the evaluation of casaflux%Pleach had two versions, one specific to ESM1.5 (selected via an ifdef) and the alternat for all other cases. Following the code through, the ESM1.5 version had a hard-wired value (1.e-4) for casaflux%fPleach. casaflux%fPleach is filled from xfPleach which is read in from the pftlookup file. The ESM1.5 specific code can be safely removed with no change to the output if xfPleach is set to 1.e-4 in the pftlookup file. Note that there are versions of the pftlookup with xfPleach = 5.e-4. I am not aware of when/who set it to this value and whether it is considered to be better/more realistic.
Fixes #278
Please add a reviewer when ready for …
> Removed ESM15 version with hard-wired xfpleach parameter, #278

- src/science/casa-cnp/casa_cnp.F90
Non-ESM15 code versions had a condition on the calculation of dNplantdt(:.wood) to only do the calculation for woody pfts, having first set it to zero for all pfts. An ifndef was used to ignore the condition when ESM15 was defined YES.
The was no apparent reason why ESM15 could not use the condition so the special case was removed.
For clarity the condition was re-written as an IF/THEN.
dPplantdt(:,wood) is calculated in the same way as dNplantdt but had no condition. For consistency, a similar condition has been added so that nitrogen and phosphorus are treated the same way.
Fixes #423
- [X ] Bug fix / code clean up
- [X ] I have checked my code/text and corrected any misspellings …
> Remove ESM15 special case related to lnonwood condition on dNplantdt(wood)

- documentation/docs/developer_guide/other_resources/api.md
- documentation/mkdocs.yml
The `api.md` page (currently https://cable.readthedocs.io/en/latest/developer_guide/other_resources/api/) does not contain any useful information. This change points the API link under Developer Guide to the Ford documentation directly and removes `api.md`.
----
📚 Documentation preview 📚: https://cable--442.org.readthedocs.build/en/442/
> Point API link to Ford docs directly

- core/biogeochem/POPLUC.F90
- core/biogeochem/casa_inout.F90
- core/biogeophys/cable_common.F90
- offline/cable_cru_TRENDY.F90
- offline/cable_input.F90
The model did not compile with gfortran v14.2.
Possible dimension names in input files are defined as a character arrays in cable_common_module. They have different character lengths. The current notation is not Fortran standard compliant. I replaced
```
CHARACTER(LEN=16), DIMENSION(5), PARAMETER :: LatNames = &
["latitude", "lat", "lats", "y", "Latitude"]
```
with
```
CHARACTER(LEN=*), DIMENSION(*), PARAMETER :: LatNames = &
[CHARACTER(LEN=8) :: "latitude", "lat", "lats", "y", "Latitude"]
```
Same for `LonNames` and `TimeNames`.
I found this very cool notation on [stackoverflow](https://stackoverflow.com/questions/21552430/gfortran-does-not-allow-character-arrays-with-varying-component-lengths).
Another error was also in cable_common, where the continuation character was within the …
> Correct array constructor for strings in CABLE-POP_TRENDY

- src/offline/cable_output.F90
- src/offline/landuse_inout.F90
Refactor the output and fence all calls to the generate_out_write_acc subroutine such that no non-allocated arrays are accessed.
Fixes #415 
----
📚 Documentation preview 📚: https://cable--456.org.readthedocs.build/en/456/
> 415 non allocated arrays accessed in output

- core/biogeophys/cable_common.F90
- core/blaze/blaze.F90
- core/blaze/simfire.F90
- offline/cable_LUC_EXPT.F90
- offline/cable_bios_met_obs_params.F90
- offline/cable_cru_TRENDY.F90
- offline/cable_driver.F90
- offline/cable_plume_mip.F90
- offline/cable_site.F90
Add a routine to handle namelist errors, that returns a much more informative error message than the baseline namelist error message. Utilises the new ```IOMSG``` specifier and the routine detailed [here](https://degenerateconic.com/namelist-error-checking.html).
Fixes #(431)
Edit: Turns out that this namelist checking routine relies on undefined behaviour. The problems I was seeing was the result of a "regression" in Intel Fortran 2023, see [this thread](https://community.intel.com/t5/Intel-Fortran-Compiler/Regression-with-quot-backspace-quot-in-2023-0/m-p/1448175). The comment from Steve Lionel in the accepted answer is important:
> The standard says, "If an error condition occurs during execution of an input/output …
> 431 add routine for more informative namelist errors

- CMakeLists.txt
- src/offline/cable_driver.F90
- src/offline/cable_driver_init.F90
- src/offline/cable_mpicommon.F90
- src/offline/cable_mpidrv.F90
- src/offline/cable_mpimaster.F90
- src/offline/cable_mpiworker.F90
Whilst looking into merging the MPI master and worker drivers (#358), @micaeljtoliveira and I have identified that the model initialisation logic is duplicated across all drivers (serial and MPI master/worker). This change adds a preliminary initialisation routine to remove code duplication and improve code clarity across each of the drivers. The remaining initialisation code in the offline drivers will be moved to this routine in later pull requests to clean up the drivers further.
----
📚 Documentation preview 📚: https://cable--440.org.readthedocs.build/en/440/
> Add initialisation routine for offline drivers

- core/biogeochem/casa_inout.F90
- core/biogeophys/cable_common.F90
- core/biogeophys/cable_diag.F90
- core/blaze/simfire.F90
- offline/cable_driver.F90
- offline/cable_input.F90
Extend the use of the ```NEWUNIT=``` specifier for acquiring io units to the rest of the active ```OPEN``` calls in the code. There is one exception, in the calls found within ```core/biogeophys/cable_diag.F90```. The units are handled a bit strangely here, with one being defined dependent on the other. Looks like it might interact with the UM coupling in a specific way, so I've left it as is at the moment.
Fixes #455 
- Fortran standards update
> Use NEWUNIT in almost all active OPEN statements

- CMakeLists.txt
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_cbm.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_rad_driver.F90
- src/coupled/ESM1.5/cable_surface_types.F90
- src/offline/cable_parameters.F90
- src/offline/cable_surface_types.F90
- src/offline/cbl_model_driver_offline.F90
- src/params/grid_constants_cbl.F90
- src/science/canopy/cbl_SurfaceWetness.F90
- src/science/canopy/cbl_init_wetfac_mod.f90
- src/science/casa-cnp/casa_variable.F90
- src/science/gw_hydro/cable_gw_hydro.F90
- src/science/roughness/cable_roughness.F90
- src/science/soilsnow/cbl_surfbv.F90
With these minor changes CABLE:main can be cloned directly into the ESM1.6 / UM7.3 code under umbase_hg3. NB:A lot of the changes are replicated from PRs that are waiting to be reviewed.
Fixes #473, #468
For ESM1.6. A library can be built directly from this code
benchcab regression tessts successful:  
[benchmark_cable_qsub.sh.o128621374.txt](https://github.com/user-attachments/files/17748080/benchmark_cable_qsub.sh.o128621374.txt)
----
📚 Documentation preview 📚: https://cable--474.org.readthedocs.build/en/474/
> changes required for ESM16

- offline/cable_driver.F90
Add the ```logn``` variable back into the namelist. This was an unintentional consequence of merged PR #460- existing configurations that have the now superfluous ```logn``` in the cable namelist will fail. The variable won't do anything, but needs to remain until configurations are updated.
Fixes #492 
> Add logn back to the cable nml

- src/offline/cable_mpicommon.F90
- src/offline/cable_mpimaster.F90
- src/offline/cable_mpiworker.F90
- src/offline/cable_parameters.F90
Fixes #490 
Working on the groundwater implementation, I have found that the function `total_soil_conductivity` depends on some GW parameters that aren't correctly implemented. This is to fix this.
Since this requires MPI to test the impact, I haven't used modelevaluation.org to analyse the results. I have run benchcab with the spatial configuration for:
1. main with `cable_user%soil_thermal_fix = .TRUE`
1. main with `cable_user%soil_thermal_fix = .FALSE`
1. this branch with `cable_user%soil_thermal_fix = .TRUE`
2. this branch with `cable_user%soil_thermal_fix = .FALSE`
Case 3 - Case 1 allow to gauge the total effect of the change. Case 2 - Case 1 give a measure of the change …
> Fix to groundwater parameter initialisations that can impact the soil conductivity

- src/science/canopy/cable_canopy.F90
- src/science/soilsnow/cbl_surfbv.F90
Reconcile ESM16: CABLE and CABLE:main excludes #497  and divergent casa-cnp/. Super quick
Fixes #500 
----
📚 Documentation preview 📚: https://cable--501.org.readthedocs.build/en/501/
> reconcile ESM16: CABLE and CABLE:main

- core/biogeochem/casa_inout.F90
- core/biogeophys/cable_common.F90
Somehow I missed a few ```NEWUNIT``` specifiers in ```OPEN``` statements. It wasn't picked up during compilation, threw a runtime error.
Fixes #502 
Did a BIOS run to make sure things were working smoothly.
> Add NEWUNIT to some OPEN statements

- src/coupled/esm16/cable_surface_types.F90
remove  this redundant FPP directive. 
Fixes #super quick one liner
----
📚 Documentation preview 📚: https://cable--508.org.readthedocs.build/en/508/
> remove  this redundant FPP directive

- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_um_init_subrs.F90
- src/coupled/ESM1.5/cable_pft_params.F90
enable parametrisation bases on rootbeta as default behaviour
Fixes #451 
----
📚 Documentation preview 📚: https://cable--453.org.readthedocs.build/en/453/
> enaable          rootbeta parametrization of froot

- src/science/canopy/cable_canopy.F90
- src/science/canopy/cbl_SurfaceWetness.F90
- src/science/canopy/cbl_latent_heat.F90
- src/science/canopy/cbl_within_canopy.F90
#496
Fixes #496
----
📚 Documentation preview 📚: https://cable--519.org.readthedocs.build/en/519/
> mods from AM3 corresponding to #496 here and a few others

- CMakeLists.txt
- core/biogeophys/cable_common.F90
- core/biogeophys/mo_utils.f90
- offline/cable_cru_TRENDY.F90
- offline/cable_input.F90
Bug fixes to compile with GFortran > v13 following the Fortran 2008 Standard.
CABLE gets compiled with the option to follow the Fortran 2008 Standard now.
The compiler flag was wrong for GFortran in `CMakeLists.txt`. It was `-std=f08` as for the Intel compiler but should be `-std=f2008`.
There were several non-standard functions used in the code, that do not work anymore with the `-std=f2008` flag:
1. getenv() - replaced by the F2003 function get_environment_variable
3. call exit(5) - replaced by stop 5
4. stop variable - stop cannot be followed by a variable (apparently), put the error code into the message above the stop
5. isnan - this was a GNU extension. Replaced it with code from [here](https://fortran-lang.discourse.group/t/challenge-testing-inf-and-nan-with-gfortran-13-ofast/6481/3 …
> Compile with GFortran following Fortran 2008 Standard

- CMakeLists.txt
- src/offline/cable_driver_common.F90
- src/offline/cable_mpimaster.F90
- src/offline/cable_mpiworker.F90
- src/offline/cable_offline_driver.F90
- src/offline/cable_serial.F90
Several changes to make the MPI and serial versions of the offline driver more similar. This is mostly to help identifying the differences between the two versions so they can later be merged.
Also moved some common code between the two versions to the `cable_driver_init_mod`, which is renamed to `cable_driver_common_mod`.
After rebasing on the head of main, benchcab's bitwise-comparisons succeed for the flux site tests:
```
2025-01-13 14:55:18,320 - INFO - benchcab.benchcab.py:391 - 0 failed, 168 passed
```
----
📚 Documentation preview 📚: https://cable--516.org.readthedocs.build/en/516/
> Offline driver refactor continued

- .github/pull_request_template.md
Added details to the PR template RE: benchcab outputs.
----
📚 Documentation preview 📚: https://cable--518.org.readthedocs.build/en/518/
> Added details around benchcab outputs to the PR template. Fixes #517

- src/offline/cable_define_types.F90
- src/util/cable_climate_type_mod.F90
Fixes #(issue)
2025-01-17 13:27:09,851 - INFO - comparison.comparison.py:73 - Success: files US-Whs_2008-2014_FLUXNET2015_Met_R0_S0_out.nc US-Whs_2008-2014_FLUXNET2015_Met_R1_S0_out.nc are identical
2025-01-17 13:27:10,097 - INFO - comparison.comparison.py:73 - Success: files US-Whs_2008-2014_FLUXNET2015_Met_R0_S1_out.nc US-Whs_2008-2014_FLUXNET2015_Met_R1_S1_out.nc are identical
2025-01-17 13:27:11,436 - INFO - comparison.comparison.py:73 - …
> use centralized version of climate type

- src/offline/cable_input.F90
Fixes #525 
I decided to add the possibility of 3D or 4D formats in met forcings for all variables, except LAI, even if the issue was seen only for CO2air. This makes all the variables treatment identical. LAI was excluded because it is a different case with more complex conditions. This focused only on the "mask" option of `metGrid` as it is the most widely used and I don't have a test case for the "land" option.
As expected all bitwise-comparison tests have failed:
```
2025-01-15 12:10:39,793 - INFO - benchcab.benchcab.py:391 - 168 failed, 0 passed
```
[Results from modelevaluation.org](https://modelevaluation.org/analyses/anywhere/nFcjg4qqHGPkB9sqE/s6k22L3WajmiS9uGv/AGbw9TkEdqikdyS …
> Include 3D and 4D read options for all met variables

- src/offline/cable_mpiworker.F90
Variables `ssnow%rtevap_sat`, `ssnow%rtevap_unsat` and  `ssnow%qrecharge` are uninitialised in all MPI worker processes and crashes the model when runtime memory checks are enabled (see #397 for more details). These variables are specifically initialised (to zero) in cable_parameters.F90 for the serial case (and for the MPI master process). Rather than communicating the initialised variables from master to worker, this change initialises the variables in the worker directly.
Although we plan to deprecate the MPI drivers in the future, this change will still be useful when comparing the behaviour of MPI vs serial during development.
Fixes #397
----
📚 Documentation preview 📚: https://cable--471.org.readthedocs.build/en/471/
> Initialise `ssnow` variables in mpiworker

- src/coupled/ACCESS-CM2/cable_cbm.F90
- src/coupled/AM3/control/cable/CM3/cbl_cbm_mod.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_cbm.F90
- src/offline/cbl_model_driver_offline.F90
As per #539 it would be useful (for coupled applications) if there was no need for `%osnowd` in the restart file.
The current need stems from the call to `snow_aging()` prior to the first setting of `%osnowd` as part of the time stepping.
Moving the call to `snow_aging` to after the call to `soil_snow` (or `sli_main`) avoids this as both `osnowd` and `snowd` are evaluated in those routines.
This change will not be bitwise reproducible - but is likely scientifically of no impact. 
There are partner changes that are needed in the coupled routines (particularly CM2 and AM3) which will be included in this issue - but have not been tested.
Once accepted we may also be able to review/remove the need for `osnowd` in the offline …
> move snow aging call to avoid need for osnowd in restart

- src/coupled/ESM1.5/CABLEfilesFromESM1.5/allocate_soil_params_cbl.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/allocate_veg_params_cbl.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_cbm.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_define_types.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_explicit_driver.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_hyd_driver.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_implicit_driver.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_rad_driver.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_read_nml.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_um_init.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_um_init_subrs.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_um_tech.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cbl_LAI_canopy_height.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cbl_um_init_soil.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cbl_um_init_soilsnow.F90
- src/coupled/ESM1.5/CABLEfilesFromESM1.5/cbl_um_update_soilsnow.F90
- src/coupled/ESM1.5/cable_pft_params_mod.F90
- src/coupled/ESM1.5/cable_soil_params_mod.F90
- src/coupled/ESM1.5/casa_landuse.F90
- src/coupled/ESM1.5/casa_um_inout.F90
- src/coupled/ESM1.5/pack_mod_cbl.F90
- src/coupled/shared/cable_soil_type_mod.F90
- src/coupled/shared/cable_veg_type_mod.F90
Reconcile developments in ESM1.6 with CABLE:main
There are changes across utilities since directories as well BUT here it is only those in coupled/ that are considered.
Post shuffling these files around to facilitate building a library. What happens to them is irrelevant really. 
These modified and added files are from dev-access-esm1.6. 
So - I haven't actually done the testing BUT considering none of these fits are even in the build they cant impact anything
----
📚 Documentation preview 📚: https://cable--551.org.readthedocs.build/en/551/
> reconcile with dev-access-esm1.6 - interface code

- documentation/docs/user_guide/inputs/cable_nml.md
- documentation/docs/user_guide/inputs/index.md
- src/offline/cable.nml
- src/offline/cable_driver_common.F90
- src/util/cable_common.F90
- src/util/cable_runtime_opts_mod.F90
In ESM1.6 we have upgraded snmin(the threshold snow depth triggering 3-layer treatment) to a runtime configurable constant.
Merging ESM1.6 code we already have modifications to cable_common and cable_runtime_opts. Strictly speaking, it shouldn't be necessary to make any mods to offline at all. 
However, with some very minor modifications (on top of those that are already coming through the merge anyway), we can implement snmin as  a runtime configurable constant in offline as well.
put snmin=1.0 in cable.nml to reproduce main.
Enhancement following ESM1.6
2025-03-03 16:40:25,871 - INFO - benchcab.benchcab.py:391 - 0 failed, 20 passed
----
📚 Documentation preview 📚: https://cable--552.org.readthedocs.build/en/552/
> reconcile with dev-access-esm1.6 - util- snmin threshold thru namelist 

- src/offline/cable_driver_common.F90
- src/offline/cable_mpimaster.F90
- src/offline/cable_mpimaster_stub.F90
- src/offline/cable_offline_driver.F90
- src/offline/cable_serial.F90
The trunk_sumbal value is still used in the offline driver when a consistency check file cannot be find. To avoid using a garbage value and potentially causing an exception, this change moves the tolerance calculation and the trunk_sumbal initialisation into a single subroutine so that trunk_sumbal is used only when it is successfully read from the the consistency check file.
```
2025-03-25 11:11:26,592 - INFO - benchcab.benchcab.py:380 - Running comparison tasks...
2025-03-25 11:11:26,627 - INFO - benchcab.benchcab.py:381 - tasks: 168 (models: 2, sites: 42, science configurations: 4)
2025-03-25 11:14:17,701 - INFO - benchcab.benchcab.py:391 - 0 failed, 168 passed
```
----
📚 Documentation preview 📚: …
> Avoid using uninitialised trunk_sumbal

- offline/cable_cru_TRENDY.F90
Identified some meteorology bugs that caused issues during the later spinup stages. Specific bugs are:
* Incorrect year was retrieved for previous/next day met variables during spin-up
* Calculation of length of year became incorrect over time due to implicit ```SAVE```
Fixes #[570](https://github.com/CABLE-LSM/CABLE/issues/570)
This is not being pushed into the ```main``` branch.
> Fix the meteorology bugs identified in issue

- .github/workflows/model-build-test-ci.yml
- documentation/docs/developer_guide/documentation_guidelines/index.md
The build CI and the link checker in the documentation were failing. This PR solves both issues.
Updating the CI action version to fix a problem with the build (see [CI issue](https://github.com/ACCESS-NRI/build-ci/issues/215))
Update link to ACCESS-Hive docs with new URL.
----
📚 Documentation preview 📚: https://cable--594.org.readthedocs.build/en/594/
> Fix automatic tests

- CMakeLists.txt
- src/offline/cable_input.F90
Bug fixes for GCC build (compiler version GNU Fortran (GCC) 13.2.0).
```
2025-08-08 14:03:53,983 - INFO - benchcab.benchcab.py:352 - Running fluxsite tasks...
2025-08-08 14:03:54,010 - INFO - benchcab.benchcab.py:353 - tasks: 336 (models: 2, sites: 42, science configurations: 4)
2025-08-08 14:36:58,173 - INFO - benchcab.benchcab.py:363 - 0 failed, 336 passed
2025-08-08 14:37:07,027 - INFO - benchcab.benchcab.py:380 - Running comparison tasks...
2025-08-08 14:37:07,050 - INFO - benchcab.benchcab.py:381 - tasks: 168 (models: 2, sites: 42, science configurations: 4)
2025-08-08 14:39:57,419 - INFO - benchcab.benchcab.py:391 - 0 failed, 168 passed
```
----
📚 Documentation preview 📚: …
> Fix GCC build

- CMakeLists.txt
Seems the UM7 spack package requires the library to be named the same as the SPR to be findable, in particular the UM7 spack package which prepares the FCM build. In my testing I changed the static library name to be ```cable```, but I changed it back to ```cable_science``` in the previous PR, forgetting the issues this caused in the UM7 SPR.
----
📚 Documentation preview 📚: https://cable--609.org.readthedocs.build/en/609/
> Change name of static library for spack reasons

- core/biogeophys/cable_common.F90
- offline/cable_cru_TRENDY.F90
The ```CABLE-POP_TRENDY``` branch of the code currently sets ```cable_user%calc_fdiff=.FALSE.``` by default. The only place this was modified was in the CRU meteorology setup, so would effectively break anyone else's simulation not using this workflow who was unaware of this change.
This change changes the default to ```cable_user%calc_fdiff=.TRUE.```, so that the code computes the direct and diffuse fractions via the spitter function. The check used in the CRU/TRENDY has been moved to initialisation. If the user turns off diffuse fraction calculation (via the ```ReadDiffFrac=.TRUE.``` option in the CRU namelist), but doesn't also provide a dataset to read from, the code will now throw an error.
This is not an ideal fix, as we should be checking against the ```cable_user%calc_fdiff``` …
> Make the code compute the diffuse fraction by default

- .github/workflows/ci.yml
References ACCESS-NRI/build-ci#239
Now that the above linked PR is merged, we can transition away from the commit hashes for the refs. Specifically:
* We are now on the `v2` branch for the `ci-github-hosted.yml` workflow. This means that you will get updates, but they are compatible with the current workflow inputs.
* Moved from the temp branch on `spack-config` to `main`
* Updated container image from `:rocky-v1.0` to `:rocky-v1.0-2025.09.000` (which updates how spack configuration scopes work)
* Added some comments as well! 
----
📚 Documentation preview 📚: https://cable--612.org.readthedocs.build/en/612/
> `build-ci`: Change to Stable Refs

- offline/cable_output.F90
Timestep for output was written as:
```
timetemp(1) = REAL(REAL(ktau-backtrack)*dels,r_2)
```
in  cable_output.F90. This led to imprecisions after 134 217 000 seconds, which is timestep ktau = 74 565 for half hour data, dels = 1800., and corresponds to less than 3.5 years. These are 2^27 seconds. The fraction of a 32-bit real is normally represented with 23 bits; I do not know why the imprecision starts only at 2^27.
The imprecision are about 8 seconds on my computer (Intel Mac), i.e. the dates are, for example, 1994-04-03T18:00:00, 1994-04-03T18:29:52, 1994-04-03T19:00:00, 1994-04-03T19:30:08, 1994-04-03T20:00:00, ...
Solution: do the multiplication in double precision:
```
timetemp(1) = real(ktau - backtrack, r_2) * real(dels, r_2)
```
> Corrected imprecision of timestep in output
